# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_building_control.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BuildingControl(object):
    def setupUi(self, BuildingControl):
        BuildingControl.setObjectName("BuildingControl")
        BuildingControl.resize(341, 600)
        BuildingControl.setMaximumSize(QtCore.QSize(360, 600))
        self.floor_box = QtWidgets.QGroupBox(BuildingControl)
        self.floor_box.setGeometry(QtCore.QRect(10, 10, 311, 301))
        self.floor_box.setObjectName("floor_box")
        self.gridLayoutWidget = QtWidgets.QWidget(self.floor_box)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 291, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spin_z = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.spin_z.setMinimum(-99.99)
        self.spin_z.setSingleStep(0.1)
        self.spin_z.setObjectName("spin_z")
        self.gridLayout.addWidget(self.spin_z, 7, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 2, 2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 4, 1, 1)
        self.spin_x = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.spin_x.setMinimum(-100.0)
        self.spin_x.setSingleStep(0.1)
        self.spin_x.setObjectName("spin_x")
        self.gridLayout.addWidget(self.spin_x, 7, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 2, 8, 1)
        self.label_floors = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_floors.setObjectName("label_floors")
        self.gridLayout.addWidget(self.label_floors, 0, 0, 2, 2)
        self.label_floor_thickness = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_floor_thickness.setObjectName("label_floor_thickness")
        self.gridLayout.addWidget(self.label_floor_thickness, 4, 0, 2, 2)
        self.label_rooms = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_rooms.setObjectName("label_rooms")
        self.gridLayout.addWidget(self.label_rooms, 2, 0, 2, 2)
        self.spin_floor_thickness = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.spin_floor_thickness.setMinimum(0.1)
        self.spin_floor_thickness.setMaximum(2.0)
        self.spin_floor_thickness.setSingleStep(0.05)
        self.spin_floor_thickness.setProperty("value", 0.3)
        self.spin_floor_thickness.setObjectName("spin_floor_thickness")
        self.gridLayout.addWidget(self.spin_floor_thickness, 4, 3, 2, 2)
        self.spin_rooms = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spin_rooms.setMinimum(1)
        self.spin_rooms.setMaximum(20)
        self.spin_rooms.setObjectName("spin_rooms")
        self.gridLayout.addWidget(self.spin_rooms, 2, 3, 2, 2)
        self.spin_floors = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spin_floors.setAccelerated(False)
        self.spin_floors.setMinimum(1)
        self.spin_floors.setObjectName("spin_floors")
        self.gridLayout.addWidget(self.spin_floors, 0, 3, 2, 2)
        self.show_check = QtWidgets.QCheckBox(self.floor_box)
        self.show_check.setGeometry(QtCore.QRect(50, 230, 91, 19))
        self.show_check.setChecked(True)
        self.show_check.setObjectName("show_check")
        self.lock_check = QtWidgets.QCheckBox(self.floor_box)
        self.lock_check.setGeometry(QtCore.QRect(50, 260, 91, 19))
        self.lock_check.setObjectName("lock_check")
        self.delete_button = QtWidgets.QPushButton(self.floor_box)
        self.delete_button.setGeometry(QtCore.QRect(160, 240, 93, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.delete_button.setPalette(palette)
        self.delete_button.setObjectName("delete_button")
        self.room_box = QtWidgets.QGroupBox(BuildingControl)
        self.room_box.setGeometry(QtCore.QRect(10, 320, 311, 241))
        self.room_box.setObjectName("room_box")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.room_box)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 30, 251, 191))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_room_width = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_room_width.setObjectName("label_room_width")
        self.gridLayout_2.addWidget(self.label_room_width, 3, 0, 1, 1)
        self.label_room_height = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_room_height.setObjectName("label_room_height")
        self.gridLayout_2.addWidget(self.label_room_height, 4, 0, 1, 1)
        self.spin_room_length = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spin_room_length.setDecimals(1)
        self.spin_room_length.setMinimum(2.0)
        self.spin_room_length.setMaximum(50.0)
        self.spin_room_length.setSingleStep(0.2)
        self.spin_room_length.setProperty("value", 10.0)
        self.spin_room_length.setObjectName("spin_room_length")
        self.gridLayout_2.addWidget(self.spin_room_length, 1, 1, 1, 1)
        self.spin_room_width = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spin_room_width.setDecimals(1)
        self.spin_room_width.setMinimum(2.0)
        self.spin_room_width.setMaximum(50.0)
        self.spin_room_width.setSingleStep(0.2)
        self.spin_room_width.setProperty("value", 5.0)
        self.spin_room_width.setObjectName("spin_room_width")
        self.gridLayout_2.addWidget(self.spin_room_width, 3, 1, 1, 1)
        self.spin_room_height = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spin_room_height.setDecimals(1)
        self.spin_room_height.setMinimum(2.0)
        self.spin_room_height.setMaximum(50.0)
        self.spin_room_height.setSingleStep(0.2)
        self.spin_room_height.setProperty("value", 5.0)
        self.spin_room_height.setObjectName("spin_room_height")
        self.gridLayout_2.addWidget(self.spin_room_height, 4, 1, 1, 1)
        self.label_room_length = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_room_length.setFont(font)
        self.label_room_length.setWordWrap(False)
        self.label_room_length.setObjectName("label_room_length")
        self.gridLayout_2.addWidget(self.label_room_length, 1, 0, 1, 1)
        self.label_wall_thickness = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_wall_thickness.setObjectName("label_wall_thickness")
        self.gridLayout_2.addWidget(self.label_wall_thickness, 5, 0, 1, 1)
        self.spin_wall_thickness = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spin_wall_thickness.setMinimum(0.05)
        self.spin_wall_thickness.setMaximum(2.0)
        self.spin_wall_thickness.setSingleStep(0.05)
        self.spin_wall_thickness.setProperty("value", 0.1)
        self.spin_wall_thickness.setObjectName("spin_wall_thickness")
        self.gridLayout_2.addWidget(self.spin_wall_thickness, 5, 1, 1, 1)

        self.retranslateUi(BuildingControl)
        QtCore.QMetaObject.connectSlotsByName(BuildingControl)

    def retranslateUi(self, BuildingControl):
        _translate = QtCore.QCoreApplication.translate
        BuildingControl.setWindowTitle(_translate("BuildingControl", "Form"))
        self.floor_box.setTitle(_translate("BuildingControl", "楼层参数"))
        self.label_2.setText(_translate("BuildingControl", "x坐标"))
        self.label.setText(_translate("BuildingControl", "位置"))
        self.label_3.setText(_translate("BuildingControl", "z坐标"))
        self.label_floors.setText(_translate("BuildingControl", "层数"))
        self.label_floor_thickness.setText(_translate("BuildingControl", "层间厚度"))
        self.label_rooms.setText(_translate("BuildingControl", "每层房间数"))
        self.show_check.setText(_translate("BuildingControl", "显示"))
        self.lock_check.setText(_translate("BuildingControl", "锁定"))
        self.delete_button.setText(_translate("BuildingControl", "删除"))
        self.room_box.setTitle(_translate("BuildingControl", "房间参数"))
        self.label_room_width.setText(_translate("BuildingControl", "房间宽度"))
        self.label_room_height.setText(_translate("BuildingControl", "房间高度"))
        self.label_room_length.setText(_translate("BuildingControl", "房间长度    "))
        self.label_wall_thickness.setText(_translate("BuildingControl", "墙厚度"))
