# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_model_page.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModelPage(object):
    def setupUi(self, ModelPage):
        ModelPage.setObjectName("ModelPage")
        ModelPage.resize(1000, 571)
        ModelPage.setMinimumSize(QtCore.QSize(1000, 0))
        self.tabWidget = QtWidgets.QTabWidget(ModelPage)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 360, 571))
        self.tabWidget.setMinimumSize(QtCore.QSize(360, 500))
        self.tabWidget.setMaximumSize(QtCore.QSize(360, 600))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.model_page = QtWidgets.QWidget()
        self.model_page.setObjectName("model_page")
        self.floor_box = QtWidgets.QGroupBox(self.model_page)
        self.floor_box.setGeometry(QtCore.QRect(20, 10, 311, 201))
        self.floor_box.setObjectName("floor_box")
        self.gridLayoutWidget = QtWidgets.QWidget(self.floor_box)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 251, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_floor_thickness = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_floor_thickness.setObjectName("label_floor_thickness")
        self.gridLayout.addWidget(self.label_floor_thickness, 2, 0, 1, 1)
        self.label_floors = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_floors.setObjectName("label_floors")
        self.gridLayout.addWidget(self.label_floors, 0, 0, 1, 1)
        self.label_rooms = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_rooms.setObjectName("label_rooms")
        self.gridLayout.addWidget(self.label_rooms, 1, 0, 1, 1)
        self.spin_rooms = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spin_rooms.setMinimum(1)
        self.spin_rooms.setMaximum(20)
        self.spin_rooms.setObjectName("spin_rooms")
        self.gridLayout.addWidget(self.spin_rooms, 1, 1, 1, 1)
        self.spin_floors = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spin_floors.setAccelerated(False)
        self.spin_floors.setMinimum(1)
        self.spin_floors.setObjectName("spin_floors")
        self.gridLayout.addWidget(self.spin_floors, 0, 1, 1, 1)
        self.spin_floor_thickness = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.spin_floor_thickness.setMinimum(0.1)
        self.spin_floor_thickness.setMaximum(2.0)
        self.spin_floor_thickness.setSingleStep(0.05)
        self.spin_floor_thickness.setProperty("value", 0.3)
        self.spin_floor_thickness.setObjectName("spin_floor_thickness")
        self.gridLayout.addWidget(self.spin_floor_thickness, 2, 1, 1, 1)
        self.room_box = QtWidgets.QGroupBox(self.model_page)
        self.room_box.setGeometry(QtCore.QRect(20, 230, 311, 241))
        self.room_box.setObjectName("room_box")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.room_box)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 30, 251, 191))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_room_width = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_room_width.setObjectName("label_room_width")
        self.gridLayout_2.addWidget(self.label_room_width, 3, 0, 1, 1)
        self.label_room_height = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_room_height.setObjectName("label_room_height")
        self.gridLayout_2.addWidget(self.label_room_height, 4, 0, 1, 1)
        self.spin_room_length = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spin_room_length.setDecimals(1)
        self.spin_room_length.setMinimum(2.0)
        self.spin_room_length.setMaximum(50.0)
        self.spin_room_length.setSingleStep(0.2)
        self.spin_room_length.setProperty("value", 10.0)
        self.spin_room_length.setObjectName("spin_room_length")
        self.gridLayout_2.addWidget(self.spin_room_length, 1, 1, 1, 1)
        self.spin_room_width = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spin_room_width.setDecimals(1)
        self.spin_room_width.setMinimum(2.0)
        self.spin_room_width.setMaximum(50.0)
        self.spin_room_width.setSingleStep(0.2)
        self.spin_room_width.setProperty("value", 5.0)
        self.spin_room_width.setObjectName("spin_room_width")
        self.gridLayout_2.addWidget(self.spin_room_width, 3, 1, 1, 1)
        self.spin_room_height = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spin_room_height.setDecimals(1)
        self.spin_room_height.setMinimum(2.0)
        self.spin_room_height.setMaximum(50.0)
        self.spin_room_height.setSingleStep(0.2)
        self.spin_room_height.setProperty("value", 5.0)
        self.spin_room_height.setObjectName("spin_room_height")
        self.gridLayout_2.addWidget(self.spin_room_height, 4, 1, 1, 1)
        self.label_room_length = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_room_length.setFont(font)
        self.label_room_length.setWordWrap(False)
        self.label_room_length.setObjectName("label_room_length")
        self.gridLayout_2.addWidget(self.label_room_length, 1, 0, 1, 1)
        self.label_wall_thickness = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_wall_thickness.setObjectName("label_wall_thickness")
        self.gridLayout_2.addWidget(self.label_wall_thickness, 5, 0, 1, 1)
        self.spin_wall_thickness = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spin_wall_thickness.setMinimum(0.05)
        self.spin_wall_thickness.setMaximum(2.0)
        self.spin_wall_thickness.setSingleStep(0.05)
        self.spin_wall_thickness.setProperty("value", 0.1)
        self.spin_wall_thickness.setObjectName("spin_wall_thickness")
        self.gridLayout_2.addWidget(self.spin_wall_thickness, 5, 1, 1, 1)
        self.tabWidget.addTab(self.model_page, "")
        self.sources_page = QtWidgets.QWidget()
        self.sources_page.setObjectName("sources_page")
        self.source_selector = QtWidgets.QComboBox(self.sources_page)
        self.source_selector.setGeometry(QtCore.QRect(50, 20, 141, 31))
        self.source_selector.setCurrentText("")
        self.source_selector.setObjectName("source_selector")
        self.stackedWidget = QtWidgets.QStackedWidget(self.sources_page)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 60, 331, 501))
        self.stackedWidget.setObjectName("stackedWidget")
        self.new_source_button = QtWidgets.QPushButton(self.sources_page)
        self.new_source_button.setGeometry(QtCore.QRect(250, 20, 56, 31))
        self.new_source_button.setObjectName("new_source_button")
        self.tabWidget.addTab(self.sources_page, "")
        self.model_view = QtWidgets.QStackedWidget(ModelPage)
        self.model_view.setGeometry(QtCore.QRect(360, 0, 801, 591))
        self.model_view.setMinimumSize(QtCore.QSize(640, 500))
        self.model_view.setObjectName("model_view")

        self.retranslateUi(ModelPage)
        self.tabWidget.setCurrentIndex(0)
        self.source_selector.setCurrentIndex(-1)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ModelPage)

    def retranslateUi(self, ModelPage):
        _translate = QtCore.QCoreApplication.translate
        ModelPage.setWindowTitle(_translate("ModelPage", "Form"))
        self.floor_box.setTitle(_translate("ModelPage", "楼层参数"))
        self.label_floor_thickness.setText(_translate("ModelPage", "层间厚度"))
        self.label_floors.setText(_translate("ModelPage", "层数"))
        self.label_rooms.setText(_translate("ModelPage", "每层房间数"))
        self.room_box.setTitle(_translate("ModelPage", "房间参数"))
        self.label_room_width.setText(_translate("ModelPage", "房间宽度"))
        self.label_room_height.setText(_translate("ModelPage", "房间高度"))
        self.label_room_length.setText(_translate("ModelPage", "房间长度    "))
        self.label_wall_thickness.setText(_translate("ModelPage", "墙厚度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.model_page), _translate("ModelPage", "Model"))
        self.new_source_button.setText(_translate("ModelPage", "new"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sources_page), _translate("ModelPage", "Sources"))
