# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_wifi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WifiBox(object):
    def setupUi(self, WifiBox):
        WifiBox.setObjectName("WifiBox")
        WifiBox.resize(335, 306)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        WifiBox.setPalette(palette)
        self.groupBox = QtWidgets.QGroupBox(WifiBox)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 331, 291))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 311, 151))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 2, 1, 1)
        self.spin_z = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.spin_z.setMinimum(-99.99)
        self.spin_z.setSingleStep(0.1)
        self.spin_z.setObjectName("spin_z")
        self.gridLayout_3.addWidget(self.spin_z, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 2, 1)
        self.spin_x = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.spin_x.setMinimum(-99.99)
        self.spin_x.setSingleStep(0.1)
        self.spin_x.setObjectName("spin_x")
        self.gridLayout_3.addWidget(self.spin_x, 4, 1, 1, 1)
        self.power_slider = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.power_slider.setMinimum(10)
        self.power_slider.setMaximum(20)
        self.power_slider.setProperty("value", 15)
        self.power_slider.setOrientation(QtCore.Qt.Horizontal)
        self.power_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.power_slider.setTickInterval(1)
        self.power_slider.setObjectName("power_slider")
        self.gridLayout_3.addWidget(self.power_slider, 1, 2, 1, 2)
        self.power_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.power_label.setObjectName("power_label")
        self.gridLayout_3.addWidget(self.power_label, 1, 0, 1, 2)
        self.spin_y = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.spin_y.setMinimum(-99.99)
        self.spin_y.setSingleStep(0.1)
        self.spin_y.setObjectName("spin_y")
        self.gridLayout_3.addWidget(self.spin_y, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2)
        self.power_dbm = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.power_dbm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.power_dbm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.power_dbm.setLineWidth(1)
        self.power_dbm.setSmallDecimalPoint(False)
        self.power_dbm.setObjectName("power_dbm")
        self.gridLayout_3.addWidget(self.power_dbm, 2, 0, 1, 1)
        self.power_w = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.power_w.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.power_w.setObjectName("power_w")
        self.gridLayout_3.addWidget(self.power_w, 2, 2, 1, 1)
        self.freq_selector = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.freq_selector.setObjectName("freq_selector")
        self.freq_selector.addItem("")
        self.freq_selector.addItem("")
        self.gridLayout_3.addWidget(self.freq_selector, 0, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 1, 1, 1)
        self.show_check = QtWidgets.QCheckBox(self.groupBox)
        self.show_check.setGeometry(QtCore.QRect(50, 190, 81, 31))
        self.show_check.setChecked(True)
        self.show_check.setObjectName("show_check")
        self.lock_check = QtWidgets.QCheckBox(self.groupBox)
        self.lock_check.setGeometry(QtCore.QRect(50, 230, 81, 31))
        self.lock_check.setObjectName("lock_check")
        self.focus_button = QtWidgets.QPushButton(self.groupBox)
        self.focus_button.setGeometry(QtCore.QRect(150, 210, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.focus_button.setPalette(palette)
        self.focus_button.setObjectName("focus_button")
        self.delete_button = QtWidgets.QPushButton(self.groupBox)
        self.delete_button.setGeometry(QtCore.QRect(230, 210, 61, 31))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.delete_button.setFont(font)
        self.delete_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.delete_button.setObjectName("delete_button")

        self.retranslateUi(WifiBox)
        QtCore.QMetaObject.connectSlotsByName(WifiBox)

    def retranslateUi(self, WifiBox):
        _translate = QtCore.QCoreApplication.translate
        WifiBox.setWindowTitle(_translate("WifiBox", "Form"))
        self.groupBox.setTitle(_translate("WifiBox", "wifi参数"))
        self.label_5.setText(_translate("WifiBox", "y坐标"))
        self.label_3.setText(_translate("WifiBox", "位置"))
        self.power_label.setText(_translate("WifiBox", "发射功率(dBm)"))
        self.label_4.setText(_translate("WifiBox", "x坐标"))
        self.label.setText(_translate("WifiBox", "发射频段"))
        self.freq_selector.setItemText(0, _translate("WifiBox", "5.0GHz"))
        self.freq_selector.setItemText(1, _translate("WifiBox", "2.4GHz"))
        self.label_7.setText(_translate("WifiBox", "W"))
        self.label_6.setText(_translate("WifiBox", "z坐标"))
        self.label_2.setText(_translate("WifiBox", "dBm"))
        self.show_check.setText(_translate("WifiBox", "显示"))
        self.lock_check.setText(_translate("WifiBox", "锁定"))
        self.focus_button.setText(_translate("WifiBox", "聚焦"))
        self.delete_button.setText(_translate("WifiBox", "删除"))
